services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - db_network
 

  
    

 
volumes:
  pgdata:
networks:
  db_network: